dist: trusty
language: python
python:
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pyyaml
- python3 -m pip install pydiatra $pyflakes
script:
- ./japama generate 3
- python3 -m pydiatra japama
- python3 -m pyflakes japama

# vim:ts=2 sts=2 sw=2 et
