dist: xenial
language: python
jobs:
  include:
  - python: "3.3"
    dist: trusty
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7"
before_install:
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 3.3 ]]; then pyflakes='pyflakes<2'; fi
install:
- python3 -m pip install pyyaml
- python3 -m pip install pydiatra $pyflakes
- python3 -m pip install pygments restructuredtext-lint
script:
- ./japama generate 3
- python3 -m pydiatra japama
- python3 -m pyflakes japama
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
