#!/usr/bin/env python3

# Copyright © 2012-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse

import lib.cmd.show
import lib.cmd.generate

def main():
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers()
    subparsers.dest = 'COMMAND'  # https://bugs.python.org/issue9253
    subparsers.required = True
    for cmd in lib.cmd.show, lib.cmd.generate:
        sp = cmd.add_arg_parser(subparsers)
        sp.set_defaults(action=cmd.run)
    options = parser.parse_args()
    return options.action(options)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
