#!/usr/bin/env python3
# encoding=UTF-8

# Copyright © 2012-2024 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

import argparse
import signal
import sys

import lib.cmd.generate
import lib.cmd.show

def fix_arg_parser(ap):
    if sys.version_info < (3, 10):
        # https://bugs.python.org/issue9694
        ap._optionals.title = 'options'

def main():
    parser = argparse.ArgumentParser()
    fix_arg_parser(parser)
    subparsers = parser.add_subparsers()
    subparsers.dest = 'COMMAND'  # https://bugs.python.org/issue9253
    subparsers.required = True
    for cmd in lib.cmd.show, lib.cmd.generate:
        sp = cmd.add_arg_parser(subparsers)
        sp.set_defaults(action=cmd.run)
        fix_arg_parser(sp)
    options = parser.parse_args()
    signal.signal(signal.SIGPIPE, signal.SIG_DFL)
    return options.action(options)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
