#!/usr/bin/python3

import argparse
import os
import subprocess as ipc
import sys

import yaml

def main():
    os.chdir(sys.path[0])
    parser = argparse.ArgumentParser()
    parser.add_argument('--omit', action='store_true', help='omit passwords')
    parser.add_argument('-x', '--x-clipboard', action='store_true', help='copy the password to clipboard')
    parser.add_argument('keyword', metavar='KEYWORD')
    options = parser.parse_args()
    gpg = ipc.Popen(['gpg', '-q', '-d', 'passwords.yaml.gpg'], stdout=ipc.PIPE)
    for item in yaml.load(gpg.stdout):
        site = str(item['site'])
        if not options.keyword in site:
            continue
        password = str(item['password'])
        if '#' in password:
            continue
        user = str(item.get('user', '<none>'))
        if options.omit:
            password = '<omitted>'
        elif options.x_clipboard:
            options.x_clipboard = False
            options.omit = True
            xclip = ipc.Popen(['xclip'], stdin=ipc.PIPE, stderr=open(os.devnull, 'w'))
            xclip.stdin.write(password.encode('ASCII'))
            xclip.stdin.close()
            if xclip.wait() == 0:
                password = '<in-x-clipboard>'
            else:
                password = '<error>'
        print('{site} ({user}) {password}'.format(
            site=site, user=user, password=password)
        )
    gpg.wait()

if __name__ == '__main__':
    main()

# vim:ts=4 sw=4 et
